
%get anticipation period and video period measures from ECG/Resp data
function [anticipation_baseline,...
    anticipation,...
    video_baseline,...
    video, video_rating,...
    break_between_trials] = GetEcgAndRespMeasures...
    (peak_times,suspect_peaks, log_data)
    
%indexes for corresponding column in the log file
    video_start_col = 10;
    video_end_col = 11;
    word_on_col = 4;
    word_off_col = 5;
    video_rating_resp_times = [16, 17, 18, 19];
    
    num_trials = numel(log_data(:,1));
    anticipation_baseline = nan(num_trials,1);
    anticipation = nan(num_trials,1);
    video = nan(num_trials,1);
    video_baseline = nan(num_trials,1);
    video_rating= nan(num_trials,1);
    break_between_trials = nan(num_trials,1);
    %calc ibi
    interval = diff(peak_times);
    %need to control for if calculating in a gap
    for i = 1:num_trials
        %get timing information from log file
        
        log_file_row = log_data(i,:);
        %get baseline before anticipation
        word_on =log_file_row(word_on_col);
        baseline_anticipation_start_time = word_on - 3;
        anticipation_baseline(i) = GetMeanInterval(...
            baseline_anticipation_start_time,...
            word_on,...
            peak_times,...
            interval,...
            suspect_peaks);
        
        %get anticipation breaths
        word_off = log_file_row(word_off_col);
        expected_fear_rating_onset = word_off+8;
        anticipation(i) = GetMeanInterval(...
            word_on,...
            expected_fear_rating_onset,...
            peak_times,...
            interval,...
            suspect_peaks);
        
        %get pre video baseline
        video_start = log_file_row(video_start_col);
        pre_video_anticipation_start = video_start-3;
        video_baseline(i) = GetMeanInterval(...
            pre_video_anticipation_start,...
            video_start,...
            peak_times,...
            interval,...
            suspect_peaks);
        
        %get video breaths
        video_end = log_file_row(video_end_col);
        video(i) = GetMeanInterval(...
            video_start,...
            video_end,...
            peak_times,...
            interval,...
            suspect_peaks);
        
        %get video rating intervals
        video_rating_time = sum(log_file_row(video_rating_resp_times));
        finish_video_ratings = video_end + video_rating_time;
        video_rating(i) = GetMeanInterval(...
            video_end, ...
            finish_video_ratings, ...
            peak_times,...
            interval,...
            suspect_peaks);
        
        if(i<num_trials)
            %get start of next word
            next_log_file_row = log_data(i+1,:);
            next_trial_begins = next_log_file_row(word_on_col);
            
            break_between_trials(i) = GetMeanInterval(...
                finish_video_ratings,...
                next_trial_begins,...
                peak_times,...
                interval,...
                suspect_peaks);
        end
    end
    
end

